language: go
go:
  - "1.13.x"
  
go_import_path: golang.org/x/lint

install:
  - go get -t -v ./...
  
script:
  - go test -v -race ./...
  
matrix:
  allow_failures:
    - go: master
  fast_finish: true
